import { describe, expect, test } from "bun:test";
import { Api } from "telegram";
import {
  cleanDraftText,
  extractInlineButtons,
  mergeStreamingMessages,
  parseMiraMessage,
  type MessageLike,
} from "./parser";

describe("cleanDraftText", () => {
  test("trims whitespace", () => {
    expect(cleanDraftText("  hello  ")).toBe("hello");
  });

  test("strips Generated by Mira boilerplate", () => {
    const text = "Post body here.\n\nGenerated by Mira AI";
    expect(cleanDraftText(text)).toBe("Post body here.");
  });
});

describe("parseMiraMessage", () => {
  test("plain text message", () => {
    const msg: MessageLike = {
      id: 42,
      date: 1_700_000_000,
      message: "  Hello Reddit draft  ",
    };
    const parsed = parseMiraMessage(msg);
    expect(parsed.draftText).toBe("Hello Reddit draft");
    expect(parsed.messageId).toBe(42);
    expect(parsed.date).toBe(1_700_000_000);
    expect(parsed.buttons).toBeUndefined();
  });

  test("message with inline keyboard rows", () => {
    const markup = new Api.ReplyInlineMarkup({
      rows: [
        new Api.KeyboardButtonRow({
          buttons: [
            new Api.KeyboardButtonCallback({
              text: "Invite friend",
              data: Buffer.from("invite"),
            }),
          ],
        }),
        new Api.KeyboardButtonRow({
          buttons: [
            new Api.KeyboardButtonUrl({
              text: "Open site",
              url: "https://example.com",
            }),
          ],
        }),
      ],
    });

    const msg: MessageLike = {
      id: 7,
      date: 1,
      message: "Done!",
      replyMarkup: markup,
    };

    const parsed = parseMiraMessage(msg);
    expect(parsed.buttons).toHaveLength(2);
    expect(parsed.buttons![0][0]).toEqual({
      text: "Invite friend",
      type: "callback",
      data: Buffer.from("invite").toString("base64"),
    });
    expect(parsed.buttons![1][0]).toEqual({
      text: "Open site",
      type: "url",
      url: "https://example.com",
    });
  });
});

describe("extractInlineButtons", () => {
  test("returns undefined for non-inline markup", () => {
    expect(extractInlineButtons(undefined)).toBeUndefined();
    expect(extractInlineButtons({})).toBeUndefined();
  });
});

describe("mergeStreamingMessages", () => {
  test("concatenates draft text in order with blank line", () => {
    const merged = mergeStreamingMessages([
      { draftText: "Part one", messageId: 1, date: 1 },
      { draftText: "Part two", messageId: 2, date: 2 },
    ]);
    expect(merged).toBe("Part one\n\nPart two");
  });

  test("skips empty chunks", () => {
    const merged = mergeStreamingMessages([
      { draftText: "Only", messageId: 1, date: 1 },
      { draftText: "   ", messageId: 2, date: 2 },
      { draftText: "Last", messageId: 3, date: 3 },
    ]);
    expect(merged).toBe("Only\n\nLast");
  });
});
