import { Api } from "telegram";

/** Minimal Message shape for parsing (GramJS Message or test mocks). */
export interface MessageLike {
  id: number;
  date: number;
  message?: string;
  replyMarkup?: unknown;
}

export interface MiraInlineButton {
  text: string;
  type: "callback" | "url" | "other";
  data?: string;
  url?: string;
}

export interface ParsedMiraMessage {
  draftText: string;
  buttons?: MiraInlineButton[][];
  messageId: number;
  date: number;
}

const BOILERPLATE_PATTERNS: RegExp[] = [
  /^Generated by Mira.*$/gim,
  /^Powered by Mira.*$/gim,
];

export function cleanDraftText(text: string): string {
  let out = text.trim();
  for (const pattern of BOILERPLATE_PATTERNS) {
    out = out.replace(pattern, "").trim();
  }
  return out;
}

function parseButton(btn: Api.TypeKeyboardButton): MiraInlineButton {
  if (btn instanceof Api.KeyboardButtonCallback) {
    return {
      text: btn.text,
      type: "callback",
      data: Buffer.from(btn.data).toString("base64"),
    };
  }
  if (btn instanceof Api.KeyboardButtonUrl) {
    return { text: btn.text, type: "url", url: btn.url };
  }
  return { text: "text" in btn ? String(btn.text) : "", type: "other" };
}

export function extractInlineButtons(
  replyMarkup: unknown,
): MiraInlineButton[][] | undefined {
  if (!(replyMarkup instanceof Api.ReplyInlineMarkup)) {
    return undefined;
  }
  const rows = replyMarkup.rows.map((row) =>
    row.buttons.map((btn) => parseButton(btn)),
  );
  return rows.length > 0 ? rows : undefined;
}

export function parseMiraMessage(msg: MessageLike): ParsedMiraMessage {
  const raw = msg.message ?? "";
  return {
    draftText: cleanDraftText(raw),
    buttons: extractInlineButtons(msg.replyMarkup),
    messageId: msg.id,
    date: msg.date,
  };
}

export function mergeStreamingMessages(messages: ParsedMiraMessage[]): string {
  return messages
    .map((m) => m.draftText.trim())
    .filter((t) => t.length > 0)
    .join("\n\n");
}
